### ISSUE TITLE
Segmentation fault on arithmetic overflow

### ISSUE THREAD

**Issue by taketo1024** [johnno1962/Fortify#2]
If I run the following code with release configuration, it causes `Segmentation fault: 11`. 

```swift
import Fortify

func f(_ a: Int) {
    print(a + a)
}

do {
    try Fortify.protect {
        f(Int.max)
    }
} catch {
    print("error: \(error)")
}
```

If I add `f(2)` before `f(Int.max)`, the program prints the error as expected. 
Thank you.

**Comment by johnno1962** [comment]
Hi, must be something related to the optimiser/inlining if this is specific to a Release configuration. I'll take a look thanks!
